### ISSUE TITLE
if two resonances are very low, the voice changes constantly and alerts me. 

### ISSUE THREAD

**Issue by Haroldgomez777** [sl5net/0ad-TTS-speaking-population#1]
if two resonances are very low, the voice changes constantly and alerts me.

**Comment by sl5net** [comment]
thanks for the hint. hints at a single resource that is low are announced less often. I'll fix it when I have time.

**Comment by sl5net** [comment]
solved with this commit:

`add same message never repeat in next 15 seconds. using a HasMap for each message to remember meta-info`
https://github.com/sl5net/0ad-TTS-speaking-population/commit/adb7462ab666a4a77d87502fbdbafa3a7a760c77
